function maleFirstNames() {
	var firstNameMale = [
		{"name": "Akemi"},
		{"name": "Akihiko"},
		{"name": "Akio"},
		{"name": "Akira"},
		{"name": "Hideaki"},
		{"name": "Hirohito"},
		{"name": "Hiromasa"},
		{"name": "Hiroshi"},
		{"name": "Hisoka"},
		{"name": "Isas"},
		{"name": "Jiro"},
		{"name": "Jun"},
		{"name": "Kane"},
		{"name": "Kazuo"},
		{"name": "Ken"},
		{"name": "Kin"},
		{"name": "Kiyoshi"},
		{"name": "Makoto"},
		{"name": "Masahiro"},
		{"name": "Masao"},
		{"name": "Masato"},
		{"name": "Naoko"},
		{"name": "Saburo"},
		{"name": "Shiro"},
		{"name": "Takeshi"},
		{"name": "Taro"},
		{"name": "Tomi"},
		{"name": "Toshihiro"},
		{"name": "Yasahiro"},
		{"name": "Yasuo"},
		{"name": "Yemon"},
		{"name": "Yukio"}
			];
    return firstNameMale[Math.floor(Math.random() * firstNameMale.length)]; 
}
	  

function femaleFirstNames() {
	var firstNameFemale = [
		{"name": "Akako"},
		{"name": "Akasuki"},
		{"name": "Aki"},
		{"name": "Anzu"},
		{"name": "Ayako"},
		{"name": "Ayame"},
		{"name": "Chikako"},
		{"name": "Chiyoko"},
		{"name": "Chizu"},
		{"name": "Dai"},
		{"name": "Etsuko"},
		{"name": "Hanako"},
		{"name": "Harue"},
		{"name": "Haruko"},
		{"name": "Haya"},
		{"name": "Hideyo"},
		{"name": "Hiroko"},
		{"name": "Hisano"},
		{"name": "Hoshiko"},
		{"name": "Ima"},
		{"name": "Imako"},
		{"name": "Isamu"},
		{"name": "Iwa"},
		{"name": "Junko"},
		{"name": "Kagami"},
		{"name": "Kameko"},
		{"name": "Kameyo"},
		{"name": "Kikuko"},
		{"name": "Kimiyo"},
		{"name": "Kiwa"},
		{"name": "Kiyoshi"},
		{"name": "Kohana"},
		{"name": "Komako"},
		{"name": "Kukiko"},
		{"name": "Kyoko"},
		{"name": "Machi"},
		{"name": "Masa"},
		{"name": "Matsuko"},
		{"name": "Michiko"},
		{"name": "Mineko"},
		{"name": "Mitsuko"},
		{"name": "Namiko"},
		{"name": "Rai"},
		{"name": "Raku"},
		{"name": "Rei"},
		{"name": "Sakura"},
		{"name": "Setsuko"},
		{"name": "Shizko"},
		{"name": "Shizuyo"},
		{"name": "Tama"},
		{"name": "Tami"},
		{"name": "Tamiko"},
		{"name": "Tsuhgi"},
		{"name": "Umeko"},
		{"name": "Yoko"},
		{"name": "Yoshe"},
		{"name": "Yuki"},
		{"name": "Yukiko"}
			];
    return firstNameFemale[Math.floor(Math.random() * firstNameFemale.length)]; 
}
	  
