/*	  
  getOccupation() - returns the Randomly Generated Occupation
*/
function getOccupation(){
	let occupations = [
		{"occupation": "Ama (deep-sea pearl diver)", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Pearl"},
		{"occupation": "Arborist", "race": "Human", "trainedWeapon": "Hand-axe", "damage": "1d6", "tradeGoods": "Pouch filled with seeds"},
		{"occupation": "Armourer", "race": "Human", "trainedWeapon": "Hammer (as club)", "damage": "1d4", "tradeGoods": "Okashi gusoku (armour)*"},
		{"occupation": "Aspiring sushi chef", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "3 lbs of raw fish"},
		{"occupation": "Bandit", "race": "Human", "trainedWeapon": "Spear", "damage": "1d8", "tradeGoods": "Karuta tatami (armour)*"},
		{"occupation": "Boat builder", "race": "Human", "trainedWeapon": "Hammer (as club)", "damage": "1d4", "tradeGoods": "2 dozen iron nails"},
		{"occupation": "Bonsai artist", "race": "Human", "trainedWeapon": "Clippers (as dagger)", "damage": "1d4", "tradeGoods": "Bonsai tree"},
		{"occupation": "Calligrapher", "race": "Human", "trainedWeapon": "Short-sword", "damage": "1d6", "tradeGoods": "Calligraphy brush and fine ink"},
		{"occupation": "Carpenter", "race": "Human", "trainedWeapon": "Hammer (as club)", "damage": "1d4", "tradeGoods": "Hemp rope, 50’"},
		{"occupation": "Chopstick maker", "race": "Human", "trainedWeapon": "Chisel (as dagger)", "damage": "1d4", "tradeGoods": "Dozen pairs of chopsticks"},
		{"occupation": "Coal miner", "race": "Human", "trainedWeapon": "Pick (as battle axe)", "damage": "1d10", "tradeGoods": "Bag filled with coal"},
		{"occupation": "Firewood collector", "race": "Human", "trainedWeapon": "Hand-axe", "damage": "1d6", "tradeGoods": "Bundle of firewood"},
		{"occupation": "Fish merchant", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "10 lbs of fish"},
		{"occupation": "Fisherman", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Fishing net, 10’x10'"},
		{"occupation": "Fishing net mender", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "3’ x 3’ net"},
		{"occupation": "Fletcher", "race": "Human", "trainedWeapon": "Longbow", "damage": "1d6", "tradeGoods": "Quiver with 20 arrows"},
		{"occupation": "Folklorist", "race": "Human", "trainedWeapon": "Short sword", "damage": "1d6", "tradeGoods": "Gozo (straw matt), rolled up"},
		{"occupation": "Gambler", "race": "Human", "trainedWeapon": "Dagger", "damage": "1d4", "tradeGoods": "Playing cards"},
		{"occupation": "Gardener", "race": "Human", "trainedWeapon": "Shovel (as staff)", "damage": "1d4", "tradeGoods": "Pine cones"},
		{"occupation": "Geisha", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "A wig and geisha make-up"},
		{"occupation": "Geta (sandals) maker", "race": "Human", "trainedWeapon": "Chisel (as dagger)", "damage": "1d4", "tradeGoods": "3 pairs of sandals"},
		{"occupation": "Gobo (burdock root) farmer", "race": "Human", "trainedWeapon": "Sickle (as hand-axe)", "damage": "1d6", "tradeGoods": "Bundle of burdock root"},
		{"occupation": "Green tea farmer", "race": "Human", "trainedWeapon": "Sickle (as hand-axe)", "damage": "1d6", "tradeGoods": "Jar filled with tea leaves"},
		{"occupation": "Haiku poet", "race": "Human", "trainedWeapon": "Short-sword", "damage": "1d6", "tradeGoods": "Calligraphy brush and fine ink"},
		{"occupation": "Hair stylist", "race": "Human", "trainedWeapon": "Scissors (as dagger)", "damage": "1d4", "tradeGoods": "Hand mirror"},
		{"occupation": "Herbalist", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Bundle of herbs"},
		{"occupation": "Ikebana florist", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Bundle of cut flowers"},
		{"occupation": "Indentured servant", "race": "Human", "trainedWeapon": "Club", "damage": "1d4", "tradeGoods": "Small bag filled with dried barley"},
		{"occupation": "Inn keeper", "race": "Human", "trainedWeapon": "Club", "damage": "1d4", "tradeGoods": "Tinderbox, flint & steel"},
		{"occupation": "Kabuki theatre performer", "race": "Human", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Theatrical attire"},
		{"occupation": "Kimono maker", "race": "Human", "trainedWeapon": "Scissors (as dagger)", "damage": "1d4", "tradeGoods": "Unfinished kimono"},
		{"occupation": "Kite maker", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Yard of kite fabric"},
		{"occupation": "Kitsune geisha", "race": "Kitsune", "trainedWeapon": "Dagger", "damage": "1d4", "tradeGoods": "Wig & make-up"},
		{"occupation": "Kitsune haiku poet", "race": "Kitsune", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Quill pen & ink"},
		{"occupation": "Kitsune ink merchant", "race": "Kitsune", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "3 vials of ink"},
		{"occupation": "Kitsune musician", "race": "Kitsune", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Koto (harp)"},
		{"occupation": "Kitsune painter", "race": "Kitsune", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Set of paint brushes"},
		{"occupation": "Kitsune potter", "race": "Kitsune", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Clay, 1 lbs"},
		{"occupation": "Kitsune sake brewer", "race": "Kitsune", "trainedWeapon": "Club", "damage": "1d4", "tradeGoods": "1 bottle of sake"},
		{"occupation": "Kitsune silk dyer", "race": "Kitsune", "trainedWeapon": "Scissors (as dagger)", "damage": "1d4", "tradeGoods": "Silk, 3 yards"},
		{"occupation": "Kitsune silk merchant", "race": "Kitsune", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Kimono"},
		{"occupation": "Kitsune sword polisher", "race": "Kitsune", "trainedWeapon": "Short sword", "damage": "1d6", "tradeGoods": "Whetstone"},
		{"occupation": "Koropokuru acupuncturist", "race": "Koropokuru", "trainedWeapon": "Club", "damage": "1d4", "tradeGoods": "Pouch of acupuncture needles"},
		{"occupation": "Koropokuru calligrapher", "race": "Koropokuru", "trainedWeapon": "Sling", "damage": "1d4", "tradeGoods": "A set of calligraphy brushes"},
		{"occupation": "Koropokuru fishmonger", "race": "Koropokuru", "trainedWeapon": "Mallet (as Club)", "damage": "1d4", "tradeGoods": "Salted fish"},
		{"occupation": "Koropokuru flutist", "race": "Koropokuru", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Shakuhachi flute"},
		{"occupation": "Koropokuru herbalist", "race": "Koropokuru", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Herbs, 2 lbs"},
		{"occupation": "Koropokuru Noh performer", "race": "Koropokuru", "trainedWeapon": "Club", "damage": "1d4", "tradeGoods": "Make-up set"},
		{"occupation": "Koropokuru sushi chef", "race": "Koropokuru", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Raw fish"},
		{"occupation": "Koropokuru taiko drummer", "race": "Koropokuru", "trainedWeapon": "Drumstick (as club)", "damage": "1d4", "tradeGoods": "Taiko drum"},
		{"occupation": "Koropokuru tattooist", "race": "Koropokuru", "trainedWeapon": "Needle (as dart)", "damage": "1d4", "tradeGoods": "Vial of ink"},
		{"occupation": "Koropokuru woodcarver", "race": "Koropokuru", "trainedWeapon": "Carving knife (as dagger)", "damage": "1d4", "tradeGoods": "Block of wood"},
		{"occupation": "Koi (carp) breeder", "race": "Human", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "2 lbs of dried fish food"},
		{"occupation": "Koto (harp) performer", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Koto (harp)"},
		{"occupation": "Lantern maker", "race": "Human", "trainedWeapon": "Chisel (as dagger)", "damage": "1d4", "tradeGoods": "Cast iron lantern"},
		{"occupation": "Masseur", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Conical hat"},
		{"occupation": "Ningyozukai (puppeteer)", "race": "Human", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Puppet"},
		{"occupation": "Noh theatre performer", "race": "Human", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Theatrical attire"},
		{"occupation": "Palanquin bearer", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Wicker backpack"},
		{"occupation": "Pauper", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Bag filled with dried red beans"},
		{"occupation": "Peasant Levy", "race": "Human", "trainedWeapon": "Spear", "damage": "1d8", "tradeGoods": "Jingasa (conical war helmet)"},
		{"occupation": "Potter", "race": "Human", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "5 lbs of clay"},
		{"occupation": "Puppet maker", "race": "Human", "trainedWeapon": "Chisel (as dagger)", "damage": "1d4", "tradeGoods": "Puppet"},
		{"occupation": "Rice farmer", "race": "Human", "trainedWeapon": "Sickle (as hand-axe)", "damage": "1d6", "tradeGoods": "5 lbs of uncooked rice"},
		{"occupation": "Rice-paper maker", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "3 lbs of uncooked rice"},
		{"occupation": "Sailor", "race": "Human", "trainedWeapon": "Spear", "damage": "1d8", "tradeGoods": "Lantern, hooded"},
		{"occupation": "Sake brewer", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "3 bottles of sake"},
		{"occupation": "Sansuke (bathhouse attendant)", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Back scrubbing sponge"},
		{"occupation": "Scavenger", "race": "Human", "trainedWeapon": "Club", "damage": "1d4", "tradeGoods": "Iron pot"},
		{"occupation": "Shakuhachi (flute) performer", "race": "Human", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Skakuhachi (flute)"},
		{"occupation": "Silk dyer", "race": "Human", "trainedWeapon": "Scissors (as dagger)", "damage": "1d4", "tradeGoods": "1 yard of silk"},
		{"occupation": "Silk weaver", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "2 yards of fine silk"},
		{"occupation": "Silkworm breeder", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Jar filled with silkworm larva"},
		{"occupation": "Soya bean famer", "race": "Human", "trainedWeapon": "Sickle (as hand axe)", "damage": "1d6", "tradeGoods": "5 lbs of soya beans"},
		{"occupation": "Soya sauce brewer", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "3 bottles of soy sauce"},
		{"occupation": "Storyteller", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Bamboo canteen"},
		{"occupation": "Sumo wrestler", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "10 lbs of uncooked rice"},
		{"occupation": "Sword polisher", "race": "Human", "trainedWeapon": "Short sword", "damage": "1d6", "tradeGoods": "Sword stand"},
		{"occupation": "Taiko Drummer", "race": "Human", "trainedWeapon": "Taiko drumsticks x 2 (as clubs)", "damage": "1d4", "tradeGoods": "Taiko drum"},
		{"occupation": "Tatami mat maker", "race": "Human", "trainedWeapon": "Hammer (as club)", "damage": "1d4", "tradeGoods": "Silk rope, 50’"},
		{"occupation": "Tattoo artist", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Needles and inks"},
		{"occupation": "Tea ceremony assistant", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Jar filled with green tea powder"},
		{"occupation": "Tengu fisherman", "race": "Tengu", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Fishing rod"},
		{"occupation": "Tengu gambler", "race": "Tengu", "trainedWeapon": "Dagger", "damage": "1d4", "tradeGoods": "Playing cards"},
		{"occupation": "Tengu potter", "race": "Tengu", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "Clay pot"},
		{"occupation": "Tengu puppet maker", "race": "Tengu", "trainedWeapon": "Staff", "damage": "1d4", "tradeGoods": "3 puppets"},
		{"occupation": "Tengu sake taster", "race": "Tengu", "trainedWeapon": "Short sword", "damage": "1d6", "tradeGoods": "3 bottles of sake"},
		{"occupation": "Tengu silk merchant", "race": "Tengu", "trainedWeapon": "Short sword", "damage": "1d6", "tradeGoods": "Silk, 3 yards"},
		{"occupation": "Tengu tea maker", "race": "Tengu", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Pouch of fine tea leaves"},
		{"occupation": "Tengu tea merchant", "race": "Tengu", "trainedWeapon": "Dagger", "damage": "1d4", "tradeGoods": "Bag filled with tea leaves"},
		{"occupation": "Tengu urchin", "race": "Tengu", "trainedWeapon": "Stick (as club)", "damage": "1d4", "tradeGoods": "Begging bowl"},
		{"occupation": "Tengu vagabond", "race": "Tengu", "trainedWeapon": "Stick (as club)", "damage": "1d4", "tradeGoods": "Bundle of ratty clothes"},
		{"occupation": "Thug", "race": "Human", "trainedWeapon": "Mace", "damage": "1d6", "tradeGoods": "Karuta tatami (armour)*"},
		{"occupation": "Unskilled labourer", "race": "Human", "trainedWeapon": "Hammer (as club)", "damage": "1d4", "tradeGoods": "Dozen wooden pitons"},
		{"occupation": "Vagrant", "race": "Human", "trainedWeapon": "Walking stick (as staff)", "damage": "1d4", "tradeGoods": "Pouch containing dried tea leaves"},
		{"occupation": "Village idiot", "race": "Human", "trainedWeapon": "Spear", "damage": "1d8", "tradeGoods": "Conical hat"},
		{"occupation": "Wigmaker", "race": "Human", "trainedWeapon": "Knife (as dagger)", "damage": "1d4", "tradeGoods": "Wig"},
		{"occupation": "Wokou (pirate)", "race": "Human", "trainedWeapon": "Spear", "damage": "1d8", "tradeGoods": "Conical hat"},
		{"occupation": "Woodblock artisan", "race": "Human", "trainedWeapon": "Chisel (as dagger)", "damage": "1d4", "tradeGoods": "Woodblock print"},
		{"occupation": "Yakuza (gangster)", "race": "Human", "trainedWeapon": "Short sword", "damage": "1d6", "tradeGoods": "Tattoo needles and ink"}
        ];
    
        //return occupations[2];
	
    
		return occupations[Math.floor(Math.random() * 100)]; 
		
}
	  